### PR TITLE
added queries with employee id to TrainingProgram controller

### PR DESCRIPTION
**Pull request by omomotyuk**

### CODE REVIEW

**Comment by navogel** [comment]
Do I need to enter an entire employee object or just the ID to add to training program?

**Comment by navogel** [comment]
Why dont we just pass the employee Id as a param

**Comment by omomotyuk** [comment]
"Do I need to enter an entire employee object or just the ID to add to training program?" - 
It's in ticket description - "Request Body -> Employee Object". To pass just employee Id as param is more easy way - I agree.

**Review by navogel — COMMENTED** [review]
everything works as expected!!

**Review by navogel — APPROVED** [review]
yes!

**Pull request merged**
